INSERT INTO scientists (fullname, birthdate, birthplace)
  VALUES ('Alan Turing', '1912-06-23', 'London, England'),
         ('Steve Wozniak', '1950-08-11', 'San Jose, California'),
         ('Tim Berners-Lee', '1955-06-08', 'London, England'),
         ('Charles Babbage', '1791-12-26', 'London, England'),
         ('Grace Hopper', '1906-12-09', 'New York, New York'),
         ('Claude Shannon', '1916-04-30', 'Petoskey, Michigan'),
         ('Vint Cerf', '1943-06-23', 'New Haven, Connecticut'),
         ('Dennis Ritchie', '1941-09-09', 'Bronxville, New York'),
         ('James Gosling', '1955-05-19', 'Calgary, Alberta'),
         ('Tony Hoare', '1934-01-11', 'Colombo, Sri Lanka'),
         ('Bjarne Stroustrup', '1950-12-30', 'Aarhus, Denmark'),
         ('Margaret Hamilton', '1936-08-17', 'Paoli, Indiana'),
         ('John Carmack', '1970-08-20', 'Shawnee Mission, Kansas'),
         ('Donald Knuth', '1938-01-10', 'Milwaukee, Wisconsin'),
         ('Bill Gates', '1955-10-28', 'Seattle, Washington'),
         ('Gabe Newell', '1962-11-03', 'Seattle, Wasington'),
         ('Pavel Durov', '1984-10-10', 'Saint Petersburg, Russia'),
         ('Vitalik Buterin', '1994-01-31', 'Kolomna, Russia'),
         ('Edsger Dijkstra', '1930-05-11', 'Rotterdam, Netherlands'),
         ('Guido van Rossum', '1956-01-31', 'Haarlem, Netherlands'),
         ('Shawn Fanning', '1980-11-22', 'Brockton, Massachusetts'),
         ('Geoffrey Hinton', '1947-12-06', 'London, England'),
         ('Sergey Brin', '1973-08-21', 'Moscow, Russia'),
         ('Gottfrid Svartholm', '1984-10-17', 'Sweden'),
         ('Andrew Ng', '1976-04-18', 'United Kingdom'),
         ('Satoshi Nakamoto', null, null),
         ('Yukihiro Matsumoto', '1965-04-14', 'Japan'),
         ('Brendan Eich', '1961-07-04', 'Pittsburgh, Pennsylvania'),
         ('Ada Lovelace', '1815-12-10', 'London, England'),
         ('Linus Torvalds', '1969-12-28', 'Helsinki, Finland'),
         ('Kathleen Booth', '1922-07-09', 'Stourbridge, England'),
         ('Ken Thompson', '1943-02-04', 'New Orleans, Louisiana'),
         ('Al-Khwarizmi', null, 'Khwarazm');

INSERT INTO facts (fact, scientist_id)
  VALUES ('Known as the father of computer science', 1),
         ('Co-founded Apple Inc. along with Steve Jobs', 2),
         ('Was a contestant on Season 8 of Dancing with the Stars', 2),
         ('Known as the creator of the World Wide Web', 3),
         ('Considered by some to be the "father of the computer"', 4),
         ('Created the COBOL programming language', 5),
         ('One of the first programmers of the Harvard Mark I computer', 5),
         ('Was one of the first to devise the theory of machine-independent programming languages, which led to the development of COBOL.', 5),
         ('Most notable for the development of the C++ progarmming language', 11),
         ('Often credited with coining the term "software engineering"', 12),
         ('Known for her work leading to the development of on-board flight software for NASA''s Apollo moon missions', 12),
         ('Co-founded the video game company, id Software and was the lead programmer of its 1990s games Doom, Quake, and Wolfenstein 3D', 13),
         ('Left Microsoft in 1996 to found the video game company Valve', 16),
         ('Spent 13 years at Microsoft as the lead developer of the first three releases of the Windows operating systems', 16),
         ('Best known as one of the co-founders of the Ethereum blockchain', 18),
         ('Developed, Napster, a popular peer-to-peer file sharing platform in 1999', 21),
         ('Most noted for his work on aritifical neural networks', 22),
         ('One of the co-founders of The Pirate Bay, BitTorrent site.', 24),
         ('Is the name used by a person or persons involved in developing the Bitcoin cryptocurrency', 26),
         ('Chief designer of the Ruby programming language', 27),
         ('Also known as "Matz"', 27),
         ('His demeanor has brought about a motto in the Ruby community: "Matz is nice and so we are nice", which is often abbreviated as MINASWAN', 27),
         ('Created the JavaScript programming language', 28),
         ('Widely considered the first computer programmer due to her work on Charles Babbage''s Analytical Engine', 29),
         ('Creator and historically, the lead developer of the Linux kernal', 30),
         ('Created the distributed version control system, Git', 30),
         ('British computer scientist and matehmatician who wrote the first assembly language', 31),
         ('Persian mathematician whose name gave rise to the term "algorithm"', 33);